### PR TITLE
Fix issue #156 with GoDz mudgolem

### LINKED ISSUE #156: Godz bugged in CH2 - Creeps
Spawns but nothing happens afterwards (camera stays focused on the creeps). Assume it's because of the changes made in the CH2 - Towers section.

### PR DESCRIPTION
**Pull request by smashthestate**
- Replace entityKey param with actual string value from CustomNpcKeys enum
- Set camera on player hero after GoDz dialog

Closes #156

### CODE REVIEW

File: game/scripts/vscripts/Sections/Chapter2/SectionCreeps.ts [hunk 1]
```diff
@@ -107,15 +107,14 @@ const onStart = (complete: () => void) => {
...
-                    tg.spawnUnit(CustomNpcKeys.GodzMudGolem, godzSpawnLocation, DotaTeam.GOODGUYS, context => context[CustomNpcKeys.GodzMudGolem], true),
+                    tg.spawnUnit(CustomNpcKeys.GodzMudGolem, godzSpawnLocation, DotaTeam.GOODGUYS, CustomNpcKeys.GodzMudGolem, true),
                     tg.immediate(context => {
                         const godzMudGolem = context[CustomNpcKeys.GodzMudGolem]
                         setUnitPacifist(godzMudGolem, true);
                     }),
                     tg.setCameraTarget(context => context[CustomNpcKeys.GodzMudGolem]),
                     tg.textDialog(LocalizationKey.Script_2_Creeps_4, context => context[CustomNpcKeys.GodzMudGolem], 5),
                     tg.setCameraTarget(playerHero),
-                    tg.setCameraTarget(undefined),
```
Comment (Shushishtok) [inline game/scripts/vscripts/Sections/Chapter2/SectionCreeps.ts:118]: The camera is supposed to be unlocked. (we're still having discussions whether or not it should or not be locked, right now it sounds like we'll not be locking the camera all the time).

However, I would probably change that to pan the camera from Godz to the player quickly (I can do this, or if you want to, feel free)

Comment (smashthestate) [reply game/scripts/vscripts/Sections/Chapter2/SectionCreeps.ts:118]: I've checked the later sections (CH4 specifically) and saw camera was still locked, so I figured it was meant to be locked here too.

I'll add the pan change
