### PR TITLE
CH6 Closing - Fix skip during dialog and early-interact

### LINKED ISSUE #443: CH6 Closing - Talking to an NPC before the script text is over stops the main flow
When you get into CH6 closing Slacks and SUNSfan say goodbye, give you a rapier and the quest to destroy the enemy ancient. If you talk to an NPC before they finish you won't get the rapier nor the quest.

Possible solution: freeze hero during main dialog
Possible solution 2: don't allow dialogs until they're done talking

image

### PR DESCRIPTION
**Pull request by RobinKa**
Fixes #443 and #379

Potential issue: when skipping / over calling `stopInteract()` on all npcs even if they weren't interacting (cause we don't track that) so sends many messages to panorama.

### CODE REVIEW

File: game/scripts/vscripts/Sections/Chapter6/SectionClosing.ts [hunk 1]
```diff
@@ -104,22 +108,26 @@ class ClosingNpc {
     }
 
     interact() {
-        if (this.spawned && this.unit && unitIsValidAndAlive(this.unit)) {
-            // Play dialog
-            if (this.soundName) {
-                this.dialogToken = dg.playAudio(this.soundName, this.text, this.unit, undefined, () => this.dialogToken = undefined)
-            } else {
-                this.dialogToken = dg.playText(this.text, this.unit, 5, () => this.dialogToken = undefined)
+        if (canInteract) {
```
Comment (Perryvw) [inline game/scripts/vscripts/Sections/Chapter6/SectionClosing.ts:111]: Could you please move this if statement to the order filter? this is the wrong place to put it imo
